# Generated by Django 4.1.6 on 2023-02-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_projects_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
