# Generated by Django 4.1.6 on 2023-02-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='punctuation',
        ),
    ]
