# Generated by Django 4.1.6 on 2023-08-28 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_consult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(upload_to='images/technologies')),
                ('type_tech', models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('database', 'database'), ('cloud', 'cloud')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='rol',
        ),
        migrations.AddField(
            model_name='project',
            name='conclusion',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='db_diagram',
            field=models.ImageField(null=True, upload_to='images/projects/diagrams'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technology')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(through='core.ProjectTechnology', to='core.technology'),
        ),
    ]
