# Generated by Django 4.1.6 on 2023-09-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_technology_remove_testimonial_rol_project_conclusion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='db_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='images/projects/diagrams'),
        ),
        migrations.CreateModel(
            name='ProjectThirdparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('third_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thirdparty')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='third_parties',
            field=models.ManyToManyField(through='core.ProjectThirdparty', to='core.thirdparty'),
        ),
    ]
