# Generated by Django 4.1.6 on 2023-09-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_thirdparty_alter_project_db_diagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdparty',
            name='kind',
            field=models.CharField(choices=[('API', 'API'), ('Library', 'Library'), ('Other', 'Other')], max_length=25),
        ),
    ]
