# Generated by Django 4.1.6 on 2023-12-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_image',
            new_name='image',
        ),
    ]
